//____________________CLOTHES ACTION-TYPES
//-----------GET
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
//-----------SET
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const SET_TECH = "SET_TECH";
export const SET_CLOTHES = "SET_CLOTHES";
//____________________CART ACTION-TYPES
export const PUSH_TO_CART = "PUSH_TO_CART";
export const SET_TO_CART = "SET_TO_CART";
export const SET_TO_CART_ALREADY = "SET_TO_CART_ALREADY";
export const MINUS_PRODUCT = "MINUS_PRODUCT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";
export const DECREASE_ITEM_QTY = "DECREASE_ITEM_QTY";
//____________________SET_CURRENT_ITEM AND CURRENT ATTRIBUTES FOR IT
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const SET_CURRENT_ATTRIBUTE = "SET_CURRENT_ATTRIBUTE";
export const SET_SELECTED_ATTRIBUTE = "SET_SELECTED_ATTRIBUTE";
//____________________GET OTHER DATA (CURRENCY, CATEGORY)
export const GET_OTHER_DATA = "GET_OTHER_DATA";
//____________________SET CATEGORIES AND CURRENCIES FROM GRAPHQL
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENCIES = "SET_CURRENCIES";
//____________________SET CURRENT CURRENCY
export const SET_CURRENT_CURRENCY = "SET_CURRENT_CURRENCY";