//____________________PRODUCTS ACTION-TYPES
//____________________GET/SET CURRENT PRODUCTS CATEGORY
export const GET_CURRENT_CATEGORY_PRODUCTS = "GET_CURRENT_CATEGORY_PRODUCTS";
export const SET_CURRENT_CATEGORY_PRODUCTS = "SET_CURRENT_CATEGORY_PRODUCTS";
//____________________SET CATEGORY LOADER
export const SET_CATEGORY_LOADER = "SET_CATEGORY_LOADER";
//____________________CART ACTION-TYPES
export const PUSH_TO_CART = "PUSH_TO_CART";
export const PUSH_TO_CART_PLP = "PUSH_TO_CART_PLP";
export const SET_TO_CART = "SET_TO_CART";
export const SET_TO_CART_ALREADY = "SET_TO_CART_ALREADY";
export const MINUS_PRODUCT = "MINUS_PRODUCT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";
export const DECREASE_ITEM_QTY = "DECREASE_ITEM_QTY";
export const CLEAR_CART = "CLEAR_CART";
//____________________SET_CURRENT_ITEM AND CURRENT ATTRIBUTES FOR IT
export const GET_CURRENT_ITEM = "GET_CURRENT_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const SET_CURRENT_ATTRIBUTE = "SET_CURRENT_ATTRIBUTE";
export const SET_SELECTED_ATTRIBUTE = "SET_SELECTED_ATTRIBUTE";
//____________________GET OTHER DATA (CURRENCY, CATEGORY)
export const GET_OTHER_DATA = "GET_OTHER_DATA";
//____________________SET CATEGORIES AND CURRENCIES FROM GRAPHQL
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENCIES = "SET_CURRENCIES";
//___________________SET CURRENT ITEM LOADING STATUS
export const SET_CURRENT_ITEM_LOADER = "SET_CURRENT_ITEM_LOADER";
//____________________SET CURRENT CURRENCY
export const SET_CURRENT_CURRENCY = "SET_CURRENT_CURRENCY";
//__________________SET CART INFO 
export const GET_CART_INFO = "GET_CART_INFO";
export const SET_CART_INFO = "SET_CART_INFO";
